// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: proto/kube.proto

package kube

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KubeBackend_GetNodes_FullMethodName    = "/kube.KubeBackend/GetNodes"
	KubeBackend_GetNode_FullMethodName     = "/kube.KubeBackend/GetNode"
	KubeBackend_GetPods_FullMethodName     = "/kube.KubeBackend/GetPods"
	KubeBackend_GetPod_FullMethodName      = "/kube.KubeBackend/GetPod"
	KubeBackend_GetPodLogs_FullMethodName  = "/kube.KubeBackend/GetPodLogs"
	KubeBackend_ApplyYaml_FullMethodName   = "/kube.KubeBackend/ApplyYaml"
	KubeBackend_DeleteYaml_FullMethodName  = "/kube.KubeBackend/DeleteYaml"
	KubeBackend_UpgradeYaml_FullMethodName = "/kube.KubeBackend/UpgradeYaml"
)

// KubeBackendClient is the client API for KubeBackend service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KubeBackendClient interface {
	GetNodes(ctx context.Context, in *GetNodesRequest, opts ...grpc.CallOption) (*NodeList, error)
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*Node, error)
	GetPods(ctx context.Context, in *GetPodsRequest, opts ...grpc.CallOption) (*PodList, error)
	GetPod(ctx context.Context, in *GetPodRequest, opts ...grpc.CallOption) (*Pod, error)
	GetPodLogs(ctx context.Context, in *GetPodLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetPodLogsResponse], error)
	ApplyYaml(ctx context.Context, in *ApplyYamlRequest, opts ...grpc.CallOption) (*ApplyYamlResponse, error)
	DeleteYaml(ctx context.Context, in *ApplyYamlRequest, opts ...grpc.CallOption) (*ApplyYamlResponse, error)
	UpgradeYaml(ctx context.Context, in *UpgradeYamlRequest, opts ...grpc.CallOption) (*UpgradeYamlResponse, error)
}

type kubeBackendClient struct {
	cc grpc.ClientConnInterface
}

func NewKubeBackendClient(cc grpc.ClientConnInterface) KubeBackendClient {
	return &kubeBackendClient{cc}
}

func (c *kubeBackendClient) GetNodes(ctx context.Context, in *GetNodesRequest, opts ...grpc.CallOption) (*NodeList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeList)
	err := c.cc.Invoke(ctx, KubeBackend_GetNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubeBackendClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*Node, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Node)
	err := c.cc.Invoke(ctx, KubeBackend_GetNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubeBackendClient) GetPods(ctx context.Context, in *GetPodsRequest, opts ...grpc.CallOption) (*PodList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PodList)
	err := c.cc.Invoke(ctx, KubeBackend_GetPods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubeBackendClient) GetPod(ctx context.Context, in *GetPodRequest, opts ...grpc.CallOption) (*Pod, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Pod)
	err := c.cc.Invoke(ctx, KubeBackend_GetPod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubeBackendClient) GetPodLogs(ctx context.Context, in *GetPodLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetPodLogsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KubeBackend_ServiceDesc.Streams[0], KubeBackend_GetPodLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetPodLogsRequest, GetPodLogsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KubeBackend_GetPodLogsClient = grpc.ServerStreamingClient[GetPodLogsResponse]

func (c *kubeBackendClient) ApplyYaml(ctx context.Context, in *ApplyYamlRequest, opts ...grpc.CallOption) (*ApplyYamlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyYamlResponse)
	err := c.cc.Invoke(ctx, KubeBackend_ApplyYaml_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubeBackendClient) DeleteYaml(ctx context.Context, in *ApplyYamlRequest, opts ...grpc.CallOption) (*ApplyYamlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyYamlResponse)
	err := c.cc.Invoke(ctx, KubeBackend_DeleteYaml_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubeBackendClient) UpgradeYaml(ctx context.Context, in *UpgradeYamlRequest, opts ...grpc.CallOption) (*UpgradeYamlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpgradeYamlResponse)
	err := c.cc.Invoke(ctx, KubeBackend_UpgradeYaml_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KubeBackendServer is the server API for KubeBackend service.
// All implementations must embed UnimplementedKubeBackendServer
// for forward compatibility.
type KubeBackendServer interface {
	GetNodes(context.Context, *GetNodesRequest) (*NodeList, error)
	GetNode(context.Context, *GetNodeRequest) (*Node, error)
	GetPods(context.Context, *GetPodsRequest) (*PodList, error)
	GetPod(context.Context, *GetPodRequest) (*Pod, error)
	GetPodLogs(*GetPodLogsRequest, grpc.ServerStreamingServer[GetPodLogsResponse]) error
	ApplyYaml(context.Context, *ApplyYamlRequest) (*ApplyYamlResponse, error)
	DeleteYaml(context.Context, *ApplyYamlRequest) (*ApplyYamlResponse, error)
	UpgradeYaml(context.Context, *UpgradeYamlRequest) (*UpgradeYamlResponse, error)
	mustEmbedUnimplementedKubeBackendServer()
}

// UnimplementedKubeBackendServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKubeBackendServer struct{}

func (UnimplementedKubeBackendServer) GetNodes(context.Context, *GetNodesRequest) (*NodeList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodes not implemented")
}
func (UnimplementedKubeBackendServer) GetNode(context.Context, *GetNodeRequest) (*Node, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNode not implemented")
}
func (UnimplementedKubeBackendServer) GetPods(context.Context, *GetPodsRequest) (*PodList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPods not implemented")
}
func (UnimplementedKubeBackendServer) GetPod(context.Context, *GetPodRequest) (*Pod, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPod not implemented")
}
func (UnimplementedKubeBackendServer) GetPodLogs(*GetPodLogsRequest, grpc.ServerStreamingServer[GetPodLogsResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetPodLogs not implemented")
}
func (UnimplementedKubeBackendServer) ApplyYaml(context.Context, *ApplyYamlRequest) (*ApplyYamlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyYaml not implemented")
}
func (UnimplementedKubeBackendServer) DeleteYaml(context.Context, *ApplyYamlRequest) (*ApplyYamlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteYaml not implemented")
}
func (UnimplementedKubeBackendServer) UpgradeYaml(context.Context, *UpgradeYamlRequest) (*UpgradeYamlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpgradeYaml not implemented")
}
func (UnimplementedKubeBackendServer) mustEmbedUnimplementedKubeBackendServer() {}
func (UnimplementedKubeBackendServer) testEmbeddedByValue()                     {}

// UnsafeKubeBackendServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KubeBackendServer will
// result in compilation errors.
type UnsafeKubeBackendServer interface {
	mustEmbedUnimplementedKubeBackendServer()
}

func RegisterKubeBackendServer(s grpc.ServiceRegistrar, srv KubeBackendServer) {
	// If the following call pancis, it indicates UnimplementedKubeBackendServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KubeBackend_ServiceDesc, srv)
}

func _KubeBackend_GetNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubeBackendServer).GetNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KubeBackend_GetNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubeBackendServer).GetNodes(ctx, req.(*GetNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KubeBackend_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubeBackendServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KubeBackend_GetNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubeBackendServer).GetNode(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KubeBackend_GetPods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubeBackendServer).GetPods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KubeBackend_GetPods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubeBackendServer).GetPods(ctx, req.(*GetPodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KubeBackend_GetPod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubeBackendServer).GetPod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KubeBackend_GetPod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubeBackendServer).GetPod(ctx, req.(*GetPodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KubeBackend_GetPodLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetPodLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KubeBackendServer).GetPodLogs(m, &grpc.GenericServerStream[GetPodLogsRequest, GetPodLogsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KubeBackend_GetPodLogsServer = grpc.ServerStreamingServer[GetPodLogsResponse]

func _KubeBackend_ApplyYaml_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyYamlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubeBackendServer).ApplyYaml(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KubeBackend_ApplyYaml_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubeBackendServer).ApplyYaml(ctx, req.(*ApplyYamlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KubeBackend_DeleteYaml_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyYamlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubeBackendServer).DeleteYaml(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KubeBackend_DeleteYaml_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubeBackendServer).DeleteYaml(ctx, req.(*ApplyYamlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KubeBackend_UpgradeYaml_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpgradeYamlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubeBackendServer).UpgradeYaml(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KubeBackend_UpgradeYaml_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubeBackendServer).UpgradeYaml(ctx, req.(*UpgradeYamlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KubeBackend_ServiceDesc is the grpc.ServiceDesc for KubeBackend service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KubeBackend_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kube.KubeBackend",
	HandlerType: (*KubeBackendServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNodes",
			Handler:    _KubeBackend_GetNodes_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _KubeBackend_GetNode_Handler,
		},
		{
			MethodName: "GetPods",
			Handler:    _KubeBackend_GetPods_Handler,
		},
		{
			MethodName: "GetPod",
			Handler:    _KubeBackend_GetPod_Handler,
		},
		{
			MethodName: "ApplyYaml",
			Handler:    _KubeBackend_ApplyYaml_Handler,
		},
		{
			MethodName: "DeleteYaml",
			Handler:    _KubeBackend_DeleteYaml_Handler,
		},
		{
			MethodName: "UpgradeYaml",
			Handler:    _KubeBackend_UpgradeYaml_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetPodLogs",
			Handler:       _KubeBackend_GetPodLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/kube.proto",
}
